name: Publish version-ranges to crates.io

on:
  push:
    tags: ['version-ranges-v*']

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - run: cargo publish -p astral-version-ranges
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.ASTRAL_VERSION_RANGES_CRATES_IO_TOKEN }}
