name: Publish pubgrub to crates.io

on:
  push:
    tags: ['pubgrub-v*']

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC token exchange
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: rust-lang/crates-io-auth-action@b7e9a28eded4986ec6b1fa40eeee8f8f165559ec # v1
        id: auth
      - run: cargo publish -p astral-pubgrub
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
